# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
     DOCKERHUB_USERNAME: gottamshiva69@gmail.com  >> $GITHUB_ENV
          
     DOCKERHUB_TOKEN: dckr_pat__lS9vbasp9sUQQgKbOZIpP7VnGo  >> $GITHUB_ENV
          
jobs:  
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    -  name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
          username: ${ DOCKERHUB_USERNAME }
          password: ${ DOCKERHUB_TOKEN }
    -  name: Build and push 
       uses: docker/build-push-action@v5
       with:
          push: true
          tags: user/app:latest 
